let
    StartDate = Date.AddMonths(#date(2012,1,1),-6),
    EndDate = #date(Date.Year(DateTime.LocalNow()),12,31),
    NumberOfDays = Duration.Days( EndDate - StartDate ),
    Dates = List.Dates(StartDate, NumberOfDays+1, #duration(1,0,0,0)),
    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "FullDateAlternateKey"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"FullDateAlternateKey", type date}}),
    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([FullDateAlternateKey]), type number),
    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([FullDateAlternateKey]), type number),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([FullDateAlternateKey]), type text),
    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([FullDateAlternateKey]), type number),
    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Quarter", "Week of Year", each Date.WeekOfYear([FullDateAlternateKey]), type number),
    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([FullDateAlternateKey]), type number),
    #"Inserted Day" = Table.AddColumn(#"Inserted Week of Month", "Day", each Date.Day([FullDateAlternateKey]), type number),
    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day", "Day of Week", each Date.DayOfWeek([FullDateAlternateKey]), type number),
    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([FullDateAlternateKey]), type number),
    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day Name", each Date.DayOfWeekName([FullDateAlternateKey]), type text),
    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Day Name",{{"FullDateAlternateKey", "Data"}, {"Year", "Ano"}, {"Month", "Mês No"}, {"Month Name", "Mês Nome"}, {"Quarter", "Trim No"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Ano", type text}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type1",{{"Week of Year", "Semana/Ano No"}, {"Week of Month", "Semana/Mês No"}, {"Day", "Dia do Mês"}, {"Day of Week", "Dia da Semana"}, {"Day of Year", "Dia do Ano"}, {"Day Name", "Dia da Semana Nome"}, {"Mês Nome", "Mês"}}),
    #"Added Custom" = Table.AddColumn(#"Renamed Columns2", "Mês atual", each if Date.IsInCurrentMonth([Data]) then "Sim" else "Não"),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Mês passado", each if Date.IsInPreviousMonth([Data]) then "Sim" else "Não"),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Ano atual", each if Date.IsInCurrentYear([Data]) then "Sim" else "Não"),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Ano passado", each if Date.IsInPreviousYear([Data]) then "Sim" else "Não"),
    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "Últimos  3M", each if Date.IsInPreviousNMonths([Data],3) then "Sim" else "Não"),
    #"Added Custom4.1" = Table.AddColumn(#"Added Custom4", "Últimos  3M+", each if [Últimos  3M]= "Sim" or [Mês atual] = "Sim" then "Sim" else "Não"),
    #"Added Custom5" = Table.AddColumn(#"Added Custom4.1", "Últimos 12M", each if Date.IsInPreviousNMonths([Data],12) then "Sim" else "Não"),
    #"Added Custom9" = Table.AddColumn(#"Added Custom5", "Últimos 12M+", each if [Últimos 12M] = "Sim" or [Mês atual] = "Sim" then "Sim" else "Não"),
    #"Added Custom6" = Table.AddColumn(#"Added Custom9", "Ano Mês", each [Ano] & "-" & Text.End("00" & Number.ToText([Mês No]),2)),
    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "Futuro", each if DateTime.Date(DateTime.LocalNow()) < [Data] then "Sim" else "Não"),
    #"Added Custom8" = Table.AddColumn(#"Added Custom7", "Quinzena", each if [Dia do Mês] <= 15 then "H1" else "H2"),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom8",{{"Mês No", Int64.Type}, {"Trim No", Int64.Type}, {"Semana/Ano No", Int64.Type}, {"Semana/Mês No", Int64.Type}, {"Dia do Mês", Int64.Type}, {"Dia da Semana", Int64.Type}, {"Dia do Ano", Int64.Type}})
in
    #"Changed Type2"